### ISSUE TITLE
Please add a few snaps in the readme file

### ISSUE THREAD

**Issue by vamsi963601** [javierconcha/covid-19-Chile#1]

**Comment by javierconcha** [comment]
Hello Vamsi. 
Could you be more specific? Snaps of the website? 
Thanks.

**Comment by vamsi963601** [comment]
Yes

**Comment by javierconcha** [comment]
I tried yesterday, but it does not seem easy to add an image to the README.md file. I will look into it at some point. Do you know how? Thanks!
